---
- hosts: windows
  name: This is my Windows patching playbook
  
  
  # categories var is determined by a multi select survey in Tower.
  
  # reboot_server var is determined by a single select survey in Tower.
  
  
  
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(yes) }}'
